package com.example.quoteswithretrofitandroomdb.models

// STEP-1 this class is generated by kotlin from json converter tool

data class QuoteList(
    val count: Int,
    val lastItemIndex: Int,
    val page: Int,
    val results: List<Result>,
    val totalCount: Int,
    val totalPages: Int
)